### ISSUE TITLE
Devices with vendor partition support

### ISSUE THREAD

**Issue by yshalsager** [chenxiaolong/DualBootPatcher#1068]
As you know there're many new devices - if not all - which released with Android 8 must have separate vendor partition. Sadly DBP is missing this feature, Please add it, in addition to Oreo support (also fstab within dtb), else DBP will lose its amazing popularity.
@chenxiaolong

**Comment by chenxiaolong** [comment]
I'm actively working on this. Like you said, there are a few things remaining:

* `/vendor` support - need to update libmbdevice to allow specifying the vendor path in the YAML files and update mbtool to mount the block devices if available.
* fstab within DTB - I'd prefer not to patch the boot image for this since that would require DBP to include a DTB parser and compiler. DBP will patch `/proc/device-tree/firmware/android/` (or whatever `androidboot.android_dt_dir` points to) at runtime instead. This can be done with the upcoming libmbsystrace library, which can hijack any syscall made by a process.
* Need to add support for Oreo system properties in the pre-init system properties service
* Need to add support for Oreo's modular SELinux policies

**Comment by yshalsager** [comment]
@chenxiaolong in New devices with treble fstab is located in /vendor/etc/fstab.*
I think this can make things easier

**Comment by kykdev** [comment]
@chenxiaolong Any chance we could manually edit the fstab in dtb to make it compatible with DBP? If so, then what changes are needed? I tried removing system part from fstab in dtb and putting it back in fstab in ramdisk, it seemed to work fine with LineageOS 15.1 installed on my data slot, but had no luck with Touchwiz which is my primary.

**Comment by kykdev** [comment]
@chenxiaolong Yeap, but still no luck. Attached logs in case you might want to have a look sometime later/
[20180618.225548.tar.gz](https://github.com/chenxiaolong/DualBootPatcher/files/2111529/20180618.225548.tar.gz)

**Comment by chenxiaolong** [comment]
@kykdev Sorry, just got the chance to look at your message. I see this from the logs:
```
<11>[    1.985830]  [7:           init:    1] [2018-06-18T13:55:19.839220000+00:00][1:1][D] mbtool/init: Launching real init ...
<14>[    1.989226]  [4:           init:    1] init: init first stage started!
<14>[    1.989244]  [4:           init:    1] init: !@Boot: start init process
<14>[    1.989739]  [4:           init:    1] init: [libfs_mgr]fs_mgr_read_fstab_dt(): failed to read fstab from dt
<11>[    1.989752]  [4:           init:    1] init: !@Failed to read fstab from device tree
<14>[    1.989770]  [4:           init:    1] init: Skipped setting INIT_AVB_VERSION (not in recovery mode)
<14>[    1.989861]  [4:           init:    1] init: Loading SELinux policy
<14>[    1.992532]  [4:           init:    1] init: Compiling SELinux policy
<11>[    1.992615]  [4:           init:    1] init: Failed to read /vendor/etc/selinux/plat_sepolicy_vers.txt: No such file or directory
<11>[    1.992628]  [4:           init:    1] init: panic: rebooting to bootloader
```

The DTB is actually not the issue. It's rebooting because it can't compile and load the SELinux policy. Looking at the AOSP source code, [https://android.googlesource.com/platform/system/core/+/android-cts-8.0_r10/init/init.cpp#837](if `/system/etc/selinux/plat_sepolicy.cil` doesn't exist), then [https://android.googlesource.com/platform/system/core/+/android-cts-8.0_r10/init/init.cpp#715](it tries to load `/vendor/etc/selinux/plat_sepolicy_vers.txt`).

I don't know of a good way to fix this since the paths are on `/system` and `/vendor` and both partitions must be mounted via the fstab in the DTB (during init's early-mount stage).

An ugly hack might be to copy `/system/etc/selinux` or `/vendor/etc/selinux` in the ramdisk. That might at least allow the system to boot.

**Comment by chenxiaolong** [comment]
The long term solution to fix this in DBP is to use the not-yet-released libmbsystrace library. It'll allow DBP to hook into the `mount` syscall and change its behavior. It'll eliminate the need to touch the fstab at all.

Most of the code is done, but I still need to find the time to add support for hooking multi-threaded programs (like init).

**Comment by kykdev** [comment]
@chenxiaolong Thanks for having time to look into it. Followed your advice and injected /system/etc/selinux into ramdisk and it did the trick!
Too bad I don't have much left to play with my knox void S9+ so I won't be able to enjoy the benefits of libmbsystrace. Right now so many hacks are required to use DBP on it but I'm glad with it anyways :) Again thanks for helping me out this far.
