### ISSUE TITLE
[Android GUI] Suppport to API 16 (JellyBean)

### ISSUE THREAD

**Issue by Caio99BR** [chenxiaolong/DualBootPatcher#15]
I think the JellyBean is common in most of actual devices, so why not support in the GUI?
I have tested only changing minimum sdk but this force close when enter in ROMs menu.

**Comment by chenxiaolong** [comment]
I'm sticking to API 17 because a lot of the mbtool and libmbp code requires features in the C library that are only available in the NDK platform 17 and above. Some of the code also depends on internal storage path being `/data/media/0`, which was introduced when multi-user support was added in Android 4.2.

**Comment by Caio99BR** [comment]
So create a wiki or put this in your thread, because is not only me will ask for this support, btw thanks for fast comment.
