### ISSUE TITLE
[Request] Default ROM to boot

### ISSUE THREAD

**Issue by IncognitoJam** [chenxiaolong/DualBootPatcher#2]
Hi, I'd like to suggest a feature and I guessed that you'd be more likely to see it here than on the forums thread because it's so busy! I'd like to ask if you would consider adding a "default ROM" option which the device would always boot to rather than the last used ROM. For example, I'd want my phone to always boot to the CyanogenMod ROM instead of the TouchWiz ROM, and then I'd swap manually if I needed to use a Samsung stock-app. A further suggestion would be to remove the need for this altogether, and add some sort of "boot selection" when the device turns on (like if you dual-booted OSes on a PC) so that I can choose which ROM to boot to, and then maybe after 10 seconds automatically boot to one of the ROMs if none are chosen.

I was creating an app myself to try and solve my problems which would open on boot and let me choose which ROM to boot to (looking at your source code for how to do this), however it looks like you're working on an API (with the "allow receiving intents" in the app's settings) and I chose not to take this route and instead made your app open automatically on boot.

Would any of my suggested features be possible, and if not, how would I use your app's "API" to do this myself? Thanks!

**Comment by chenxiaolong** [comment]
Hi @Jamboozlez! A ROM selector on boot is definitely something that I would like to implement. There are two issues I can see right now. The first is that I've never done any graphics programming with the framebuffer before and from what I've seen in other codebases, the code can get quite ugly across different devices. Following from the first issue, the second is that I don't want to have separate device-specific builds of the patcher due to differences in the framebuffer code. I haven't gotten a chance to try this yet, but I'm hoping to strip down either CWM or TWRP to just the graphics layer and use that for showing the boot menu. Both are well-supported across a ton of devices and it would be much better than writing it from scratch.

As for an interim solution, how would you like to see your app work with regards to the behavior? From what I'm understanding (and I may be wrong), you'd like a small app that:

* Automatically runs on boot
* If this is the first reboot into, say, TouchWiz then don't do anything
* If this is the second or any subsequent reboot, then reboot again into the "Default" ROM

**Comment by Jamboozlez** [comment]
Hi @chenxiaolong! Thanks for the super quick reply. I've let myself down here by not checking my GitHub often!

I've never looked at programming recoveries before so I didn't realise things like "FrameBuffers" would be an issue. If only manufacturers shared their APIs and made a common platform.. That app sounds good! When the device boots, if it's already in the "Default" ROM then don't do anything (specified within the app when launched from the homescreen), but if the phone booted into any other ROM (without being requested to do so from within your app) then it should reboot and go to the "Default" ROM instead. I do see a problem where the app wouldn't be able to know if it had just turned on from the power button or if it had been requested to boot into a ROM, and wouldn't know whether or not to swap to the "Default" ROM.

**Comment by langren1353** [comment]
@chenxiaolong Can you implement a func that we can easily delete an old boot item~~

**Comment by Caio99BR** [comment]
This function is implemented on BootUI.
I think this issue can be closed
