### ISSUE TITLE
Could not connect to mbtool

### ISSUE THREAD

**Issue by SerenityS** [chenxiaolong/DualBootPatcher#26]
Sorry for my bad English.

My phone can't connect with mbtool socket.
I give root access and I'm using 8.0.0.r2092.g0a5a4e1.
I can't using 'Patch Zip File' too. Maybe its associate with socket error.

device commit (slte)  - https://github.com/chenxiaolong/DualBootPatcher/commit/50580a5adf4464ad61544c36e3b05af97ccde9e3

device info logs : https://drive.google.com/file/d/0B70olIYdy7cYUTZRLTFyUTBKVXM/view?usp=sharing

patch-file.log : http://pastebin.com/5kWWMj3F

logcat : http://pastebin.com/QUtQ5XkJ

**Comment by chenxiaolong** [comment]
Both issues are caused by the app being unable to extract `assets/data-8.0.0.r2092.g0a5a4e1.tar.xz` from the apk. Are you able to manually extract that file from the apk and also extract the file itself (the tar.xz)?

**Comment by SerenityS** [comment]
Thanks, It works when extract tar.xz files to data/data/com.github.../files/data-r2093-.../ .
But I don't know why Application can't extract tar.xz itself.

**Comment by chenxiaolong** [comment]
The issue was caused by the incorrect naming of the tar.xz. I broke `CMakeLists.txt` by accident, so the resulting filename was missing the version number (`assets/data-.tar.xz`). This is fixed by commit 723d4f5d74a9835130975b7ded47618403c38336 and is included in snapshot 8.0.0.r2096.g723d4f5. Please let me know if the new version works for you.

**Comment by SerenityS** [comment]
https://jenkins.noobdev.io/job/DualBoot_Patcher/691/
Okay, I will install new version of DualBootPatcher and notice you if the new version works.

**Comment by SerenityS** [comment]
Thanks, It works.
Close Issue
